/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.entity.Numero;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class FMenu extends javax.swing.JFrame {

    /**
     * Creates new form FMenu
     */
    public FMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbListaDeNumeros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atListaDeNumeros = new javax.swing.JTextArea();
        edAddNome = new javax.swing.JTextField();
        lbAddNovoNum = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnExibirMenorNum = new javax.swing.JButton();
        btnListarPares = new javax.swing.JButton();
        btnListarImpares = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        edCodAlterarNumero = new javax.swing.JTextField();
        lbCodAlterarNumero = new javax.swing.JLabel();
        lbNovoNumero = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        edNovoNumero = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbAlterarNomeDeletar = new javax.swing.JLabel();
        edCodDeletar = new javax.swing.JTextField();
        btnDeletar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        edNumero = new javax.swing.JTextField();
        lbNumero = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnListarTodos = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExibirMaiorNum = new javax.swing.JButton();
        btnExibirMedia = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        comboCodigos = new javax.swing.JComboBox<>();
        lbExibirCódigo = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        btnOrdenarListaCrescente = new javax.swing.JButton();
        btnOrdenarListaDecrescente = new javax.swing.JButton();
        btnApagarLista = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton10.setText("EXIBIR MÉDIA");

        jButton12.setText("jButton12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("GERENCIADOR DE NÚMEROS INTEIROS UTILIZANDO ARRAYLIST");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lbListaDeNumeros.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        lbListaDeNumeros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbListaDeNumeros.setText("Lista de Números");
        jPanel1.add(lbListaDeNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 88, 98, -1));

        atListaDeNumeros.setColumns(20);
        atListaDeNumeros.setRows(5);
        jScrollPane1.setViewportView(atListaDeNumeros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 110, 140, 270));
        jPanel1.add(edAddNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 160, 30));

        lbAddNovoNum.setText("Adicionar novo número: ");
        jPanel1.add(lbAddNovoNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 110, -1));

        btnExibirMenorNum.setText("EXIBIR MENOR NUM");
        btnExibirMenorNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirMenorNumActionPerformed(evt);
            }
        });
        jPanel1.add(btnExibirMenorNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 140, -1));

        btnListarPares.setText("LISTAR PARES");
        btnListarPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarParesActionPerformed(evt);
            }
        });
        jPanel1.add(btnListarPares, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 140, -1));

        btnListarImpares.setText("LISTAR IMPARES");
        btnListarImpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarImparesActionPerformed(evt);
            }
        });
        jPanel1.add(btnListarImpares, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 140, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar número"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(edCodAlterarNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        lbCodAlterarNumero.setText("Código");
        jPanel2.add(lbCodAlterarNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lbNovoNumero.setText("Novo número");
        jPanel2.add(lbNovoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel3.setText("Código");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        edNovoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNovoNumeroActionPerformed(evt);
            }
        });
        jPanel2.add(edNovoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 140, 230));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Deletar número"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbAlterarNomeDeletar.setText("Código");
        jPanel3.add(lbAlterarNomeDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel3.add(edCodDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, -1));

        btnDeletar.setText("DELETAR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 240, 120));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar número"));

        edNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNumeroActionPerformed(evt);
            }
        });

        lbNumero.setText("Número");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumero)
                    .addComponent(btnBuscar)
                    .addComponent(edNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 240, -1));

        btnListarTodos.setText("LISTAR TODOS");
        btnListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTodosActionPerformed(evt);
            }
        });
        jPanel1.add(btnListarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 140, -1));

        btnLimpar.setText("LIMPAR LISTA");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 140, -1));

        btnExibirMaiorNum.setText("EXIBIR MAIOR NUM");
        btnExibirMaiorNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirMaiorNumActionPerformed(evt);
            }
        });
        jPanel1.add(btnExibirMaiorNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 140, -1));

        btnExibirMedia.setText("EXIBIR MÉDIA");
        btnExibirMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirMediaActionPerformed(evt);
            }
        });
        jPanel1.add(btnExibirMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 140, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Para Desenvolvedores"));

        comboCodigos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BTN ADICIONAR", "BTN DELETAR", "BTN ALTERAR", "BTN LISTAR TODOS", "BTN LISTAR ÍMPARES", "BTN LISTAR PARES", "BTN ORDENAR CRESCENTE", "BTN ORDENAR DESCRESCENTE", "BTN EXIBIR MÉDIA", "BTN EXIBIR MAIOR NUM", "BTN EXIBIR MENOR NUM" }));
        comboCodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCodigosActionPerformed(evt);
            }
        });

        lbExibirCódigo.setText("Exibir Código dos botões");

        btnGerar.setText("GERAR");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbExibirCódigo)
                    .addComponent(btnGerar))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbExibirCódigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnGerar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 240, 150));

        btnOrdenarListaCrescente.setText("ORDENAR CRESCE.");
        btnOrdenarListaCrescente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarListaCrescenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenarListaCrescente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 140, -1));

        btnOrdenarListaDecrescente.setText("ORDENAR DECRES.");
        btnOrdenarListaDecrescente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarListaDecrescenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenarListaDecrescente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 140, -1));

        btnApagarLista.setText("APAGAR LISTA");
        btnApagarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnApagarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // OBJETO DO FORMULÁRIO
    Numero objNumero = new Numero();

    private void btnListarImparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarImparesActionPerformed
        atListaDeNumeros.setText(objNumero.listarNumerosImpares());
    }//GEN-LAST:event_btnListarImparesActionPerformed

    private void edNovoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNovoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNovoNumeroActionPerformed

    private void comboCodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCodigosActionPerformed

        //if ()
    }//GEN-LAST:event_comboCodigosActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        objNumero.adicionar(Integer.parseInt(edAddNome.getText()));
        atListaDeNumeros.setText(objNumero.listarNumeros());
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        objNumero.alterar(Integer.parseInt(edCodAlterarNumero.getText()), Integer.parseInt(edNovoNumero.getText()));
        atListaDeNumeros.setText(objNumero.listarNumeros());
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        objNumero.deletar(Integer.parseInt(edCodDeletar.getText()));
        atListaDeNumeros.setText(objNumero.listarNumeros());
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        objNumero.buscar(Integer.parseInt(edNumero.getText()));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void edNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNumeroActionPerformed

    private void btnListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodosActionPerformed
        atListaDeNumeros.setText(objNumero.listarNumeros());
    }//GEN-LAST:event_btnListarTodosActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        atListaDeNumeros.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnListarParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarParesActionPerformed
        atListaDeNumeros.setText(objNumero.listarNumerosPares());
    }//GEN-LAST:event_btnListarParesActionPerformed

    private void btnExibirMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirMediaActionPerformed
        objNumero.exibirMedia();
    }//GEN-LAST:event_btnExibirMediaActionPerformed

    private void btnOrdenarListaCrescenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarListaCrescenteActionPerformed
        atListaDeNumeros.setText(objNumero.ordenarListaCrescente());
    }//GEN-LAST:event_btnOrdenarListaCrescenteActionPerformed

    private void btnExibirMaiorNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirMaiorNumActionPerformed
        objNumero.exibirMaiorNumero();
    }//GEN-LAST:event_btnExibirMaiorNumActionPerformed

    private void btnExibirMenorNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirMenorNumActionPerformed
        objNumero.exibirMenorNumero();
    }//GEN-LAST:event_btnExibirMenorNumActionPerformed

    private void btnOrdenarListaDecrescenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarListaDecrescenteActionPerformed
        atListaDeNumeros.setText(objNumero.ordenarListaDescrescente());
    }//GEN-LAST:event_btnOrdenarListaDecrescenteActionPerformed

    private void btnApagarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarListaActionPerformed
        atListaDeNumeros.setText(null);
        objNumero.apagarLista();
    }//GEN-LAST:event_btnApagarListaActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        JOptionPane.showMessageDialog(null, "Valor: " + comboCodigos.getSelectedIndex() + "\nItem: " + comboCodigos.getSelectedItem());
        switch (comboCodigos.getSelectedIndex()) {

            case 0: // BOTÃO ADICIONAR
                JOptionPane.showMessageDialog(null, "MOSTRANDO CÓDIGO DO BOTÃO ADICIONAR: \n");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO FORMULÁRIO:\n\nprivate void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {\n                                             \n"
                        + "        objNumero.adicionar(Integer.parseInt(edAddNome.getText()));\n"
                        + "        atListaDeNumeros.setText(objNumero.listarNumeros());\n"
                        + "    }   ");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO MÉTODO adicionar():\n\npublic void adicionar(int numero) {\n"
                        + "        numerosAL.add(numero);\n"
                        + "    }");
                return;

            case 1: // BOTÃO DELETAR (deletar())
                JOptionPane.showMessageDialog(null, "MOSTRANDO O CÓDIGO DO BOTÃO DELETAR:");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO FORMULÁRIO: \n\nprivate void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {                                           \n"
                        + "        objNumero.deletar(Integer.parseInt(edCodDeletar.getText()));\n"
                        + "        atListaDeNumeros.setText(objNumero.listarNumeros());\n"
                        + "    }");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO MÉTODO deletar(): \n\npublic String deletar(int codigo) {\n"
                        + "        String lista = \"Lista de números: \\n\";\n"
                        + "\n"
                        + "        // ADICIONAR CONDIÇÃO \"VOCÊ TEM CERTEZA QUE DESEJA EXCLUIR?\"\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu array não está vazio\n"
                        + "            if ((codigo - 1) >= 0 && (codigo - 1) <= numerosAL.size()) { // verifica se o código inserido é um código válido e remove o número referente ao código informado\n"
                        + "                numerosAL.remove(codigo - 1);\n"
                        + "                JOptionPane.showMessageDialog(null, \"Código \" + codigo + \" foi deletado com sucesso!\");\n"
                        + "\n"
                        + "            } else { // se cair aqui, é porque não encontrou o código que foi inserido\n"
                        + "                JOptionPane.showMessageDialog(null, \"Este código ainda não foi cadastrado\");\n"
                        + "            }\n"
                        + "        } else { // lista vazia, atribui mensagem de erro para minha lista\n"
                        + "            lista = \"A lista de números se encontra vazia\";\n"
                        + "        }\n"
                        + "\n"
                        + "        // retorna a lista já editada\n"
                        + "        return lista;\n"
                        + "    }");
                return;

            case 2: //BOTÃO ALTERAR
                JOptionPane.showMessageDialog(null, "MOSTRANDO O CÓDIGO DO BOTÃO ALTERAR:");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO FORMULÁRIO: \n\nprivate void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {                                           \n"
                        + "        objNumero.alterar(Integer.parseInt(edCodAlterarNumero.getText()), Integer.parseInt(edNovoNumero.getText()));\n"
                        + "        atListaDeNumeros.setText(objNumero.listarNumeros());\n"
                        + "    }");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO MÉTODO alterar(): \n\npublic String alterar(int codigo, int novoNumero) { // método com parâmetros (os dois campos do formulário)\n"
                        + "        String lista = \"Lista de números: \\n\";\n"
                        + "\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu ArrayList não está vazio\n"
                        + "\n"
                        + "            if ((codigo - 1) >= 0 && (codigo - 1) <= numerosAL.size()) { // verifica se o código inserido é um código válido e seta o novo número correspondente ao código \n"
                        + "                numerosAL.set((codigo - 1), novoNumero);\n"
                        + "                JOptionPane.showMessageDialog(null, \"Código \" + codigo + \" foi alterado com sucesso!\");\n"
                        + "\n"
                        + "            } else { // se cair aqui, é porque não encontrou o código que foi inserido\n"
                        + "                JOptionPane.showMessageDialog(null, \"Este código ainda não foi cadastrado\");\n"
                        + "            }\n"
                        + "\n"
                        + "        } else { // lista vazia, atribui mensagem de erro para minha lista\n"
                        + "            lista = \"A lista de números se encontra vazia\";\n"
                        + "        }\n"
                        + "\n"
                        + "        // retorna a lista já editada\n"
                        + "        return lista;\n"
                        + "    }");
                return;

            case 3: //BOTÃO LISTAR TODOS 
                JOptionPane.showMessageDialog(null, "MOSTRANDO O CÓDIGO DO BOTÃO LISTAR TODOS: ");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO FORMULÁRIO: \n\nprivate void btnListarTodosActionPerformed(java.awt.event.ActionEvent evt) {                                               \n"
                        + "        atListaDeNumeros.setText(objNumero.listarNumeros());\n"
                        + "    } ");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO MÉTODO listarNumeros(): \n\npublic String listarNumeros() {\n"
                        + "        String lista = \"Lista de números: \\n\";\n"
                        + "\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu ArrayList não está vazio\n"
                        + "            for (int i = 0; i < numerosAL.size(); i++) { // percorrendo todos as casas do meu array e adicionando o número novo na lista\n"
                        + "                lista += \"Cód \" + (i + 1) + \" - \" + numerosAL.get(i) + \"\\n\";\n"
                        + "            }\n"
                        + "        } else { // lista vazia, atribui mensagem de erro para minha lista\n"
                        + "            lista = \"A lista de números se encontra vazia\";\n"
                        + "        }\n"
                        + "\n"
                        + "        // retorna a lista já editada\n"
                        + "        return lista;\n"
                        + "    }");
                return;

            case 4: //BOTÃO LISTAR ÍMPARES
                JOptionPane.showMessageDialog(null, "MOSTRANDO O CÓDIGO DO BOTÃO LISTAR ÍMPARES:");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO FORMULÁRIO: \n\nprivate void btnListarImparesActionPerformed(java.awt.event.ActionEvent evt) {                                                 \n"
                        + "        atListaDeNumeros.setText(objNumero.listarNumerosImpares());\n"
                        + "    }");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO MÉTODO listarNumerosImpares(): \n\npublic String listarNumerosImpares() {\n"
                        + "        String listaImpares = \"Lista de números ímpares: \\n\"; // atribuindo a variável lista\n"
                        + "\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu array não está vazio\n"
                        + "            for (int i = 0; i < numerosAL.size(); i++) { // percorrendo todos as \"casas\" do meu array\n"
                        + "                if (numerosAL.get(i) % 2 != 0) {\n"
                        + "                    listaImpares += \"Cód \" + (i + 1) + \" - \" + numerosAL.get(i) + \"\\n\";\n"
                        + "                }\n"
                        + "            }\n"
                        + "        } else { // lista vazia, atribui mensagem para minha lista\n"
                        + "            listaImpares = \"A lista de números se encontra vazia\";\n"
                        + "        }\n"
                        + "\n"
                        + "        return listaImpares;\n"
                        + "    }");
                return;

            case 5: //BOTÃO LISTAR PARES
                JOptionPane.showMessageDialog(null, "MOSTRANDO O CÓDIGO DO BOTÃO LISTAR PARES: ");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO FORMULÁRIO: \n\nprivate void btnListarParesActionPerformed(java.awt.event.ActionEvent evt) {                                               \n"
                        + "        atListaDeNumeros.setText(objNumero.listarNumerosPares());\n"
                        + "    } ");
                JOptionPane.showMessageDialog(null, "CÓDIGO DO MÉTODO listarNumerosPares(): \n\npublic String listarNumerosPares() {\n"
                        + "        String listaPares = \"Lista de números ímpares: \\n\"; // atribuindo a variável lista\n"
                        + "\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu array não está vazio\n"
                        + "            for (int i = 0; i < numerosAL.size(); i++) { // percorrendo todos as \"casas\" do meu array\n"
                        + "                if (numerosAL.get(i) % 2 == 0) {\n"
                        + "                    listaPares += \"Cód \" + (i + 1) + \" - \" + numerosAL.get(i) + \"\\n\";\n"
                        + "                }\n"
                        + "            }\n"
                        + "        } else { // lista vazia, atribui mensagem para minha lista\n"
                        + "            listaPares = \"A lista de números se encontra vazia\";\n"
                        + "        }\n"
                        + "\n"
                        + "        return listaPares;\n"
                        + "    }");

                return;

            case 6: //BOTÃO ORDENAR CRESCENTE
                JOptionPane.showMessageDialog(null, "MOSTRANDO O CÓDIGO DO BOTÃO ORDENAR CRESCENTE");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO FORMULÁRIO: \n\nprivate void btnOrdenarListaDecrescenteActionPerformed(java.awt.event.ActionEvent evt) {                                                           \n"
                        + "        atListaDeNumeros.setText(objNumero.ordenarListaDescrescente());\n"
                        + "    } ");
                JOptionPane.showMessageDialog(null, "CÓDIGO DO MÉTODO ordernarListaCrescente(): \n\npublic String ordenarListaCrescente() {\n"
                        + "        ArrayList<Integer> backupPAlterar = new ArrayList();\n"
                        + "        String lista = \"Lista de números: \\n\"; // atribuindo a variável lista\n"
                        + "\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu array não está vazio\n"
                        + "            for (int i = 0; i < numerosAL.size(); i++) { // percorrendo todos as casas do meu array\n"
                        + "                backupPAlterar.add(numerosAL.get(i)); // fazendo a cópia do meu array\n"
                        + "            }\n"
                        + "\n"
                        + "            Collections.sort(backupPAlterar); // ordenando meu array copiado\n"
                        + "\n"
                        + "            for (int i = 0; i < backupPAlterar.size(); i++) { // percorrendo todos as \"casas\" do meu array\n"
                        + "                lista += \"Cód \" + (i + 1) + \" - \" + backupPAlterar.get(i) + \"\\n\"; // atribui minha nova lista ordenada \n"
                        + "            }\n"
                        + "\n"
                        + "        } else { // lista vazia, atribui mensagem para minha lista\n"
                        + "            lista = \"A lista de números se encontra vazia\"; // atribui mensagem vazia\n"
                        + "        }\n"
                        + "\n"
                        + "        return lista; // retorna minha lista ordenada OU minha lista com mensagem vazia\n"
                        + "    }");
                return;

            case 7: //BOTÃO ORDENAR DECRESCENTE
                JOptionPane.showConfirmDialog(null, "MOSTRANDO O CÓDIGO DO BOTÃO ORDENAR DECRESCENTE:");

                JOptionPane.showConfirmDialog(null, "CÓDIGO DO FORMULÁRIO: \n\nprivate void btnOrdenarListaDecrescenteActionPerformed(java.awt.event.ActionEvent evt) {                                                           \n"
                        + "        atListaDeNumeros.setText(objNumero.ordenarListaDescrescente());\n"
                        + "    }");

                JOptionPane.showConfirmDialog(null, "CÓDIGO DO MÉTODO ordenarListaDecrescente(): \n\npublic String ordenarListaCrescente() {\n"
                        + "        ArrayList<Integer> backupPAlterar = new ArrayList();\n"
                        + "        String lista = \"Lista de números: \\n\"; // atribuindo a variável lista\n"
                        + "\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu array não está vazio\n"
                        + "            for (int i = 0; i < numerosAL.size(); i++) { // percorrendo todos as casas do meu array\n"
                        + "                backupPAlterar.add(numerosAL.get(i)); // fazendo a cópia do meu array\n"
                        + "            }\n"
                        + "\n"
                        + "            Collections.sort(backupPAlterar); // ordenando meu array copiado\n"
                        + "\n"
                        + "            for (int i = 0; i < backupPAlterar.size(); i++) { // percorrendo todos as \"casas\" do meu array\n"
                        + "                lista += \"Cód \" + (i + 1) + \" - \" + backupPAlterar.get(i) + \"\\n\"; // atribui minha nova lista ordenada \n"
                        + "            }\n"
                        + "\n"
                        + "        } else { // lista vazia, atribui mensagem para minha lista\n"
                        + "            lista = \"A lista de números se encontra vazia\"; // atribui mensagem vazia\n"
                        + "        }\n"
                        + "\n"
                        + "        return lista; // retorna minha lista ordenada OU minha lista com mensagem vazia\n"
                        + "    }");
                return;

            case 8: //EXIBIR MÉDIA
                JOptionPane.showMessageDialog(null, "MOSTRANDO O CÓDIGO DO BOTÃO EXIBIR MÉDIA: ");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO FORMULÁRIO \n\nprivate void btnExibirMediaActionPerformed(java.awt.event.ActionEvent evt) {                                               \n"
                        + "        objNumero.exibirMedia();\n"
                        + "    }  ");

                JOptionPane.showMessageDialog(null, "CÓDIGO DO MÉTODO exibirMedia(): \n\npublic void exibirMedia() {\n"
                        + "        int media = 0, total = 0;\n"
                        + "\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu array não está vazio\n"
                        + "            for (int i = 0; i < numerosAL.size(); i++) { // percorrendo todos as \"casas\" do meu array\n"
                        + "                total += numerosAL.get(i);\n"
                        + "            }\n"
                        + "            media = total / numerosAL.size();\n"
                        + "            JOptionPane.showMessageDialog(null, \"Média dos números: \" + media);\n"
                        + "        } else {\n"
                        + "            JOptionPane.showMessageDialog(null, \"A lista de números se encontra vazia\");\n"
                        + "        }\n"
                        + "    }\n"
                        + "");
                return;

            case 9: // BOTÃO EXIBIR MAIOR NÚMERO
                JOptionPane.showMessageDialog(null, "MOSTRANDO CÓDIGO DO BOTÃO EXIBIR MAIOR NÚMERO: ");

                JOptionPane.showMessageDialog(null, "MOSTRANDO CÓDIGO DO FORMULÁRIO: \n\nprivate void btnExibirMaiorNumActionPerformed(java.awt.event.ActionEvent evt) {                                                  \n"
                        + "        objNumero.exibirMaiorNumero();\n"
                        + "    }");

                JOptionPane.showMessageDialog(null, "MOSTRANDO CÓDIGO DO MÉTODO exibirMaiorNum(): \n\npublic void exibirMaiorNumero() {\n"
                        + "        int maiorNum = numerosAL.get(0);\n"
                        + "\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu array não está vazio\n"
                        + "            for (int i = 0; i < numerosAL.size(); i++) {\n"
                        + "\n"
                        + "                // aqui se for maior\n"
                        + "                if (numerosAL.get(i) > maiorNum) {\n"
                        + "                    maiorNum = numerosAL.get(i);\n"
                        + "                }\n"
                        + "            }\n"
                        + "            JOptionPane.showMessageDialog(null, \"MAIOR NÚMERO: \\n\\n\" + maiorNum);\n"
                        + "        }\n"
                        + "    }");
                return;
            case 10: // BOTÃO EXIBIR MENOR NÚMERO 
                JOptionPane.showMessageDialog(null, "MOSTRANDO CÓDIGO DO BOTÃO EXIBIR MENOR NÚMERO: ");

                JOptionPane.showMessageDialog(null, "MOSTRANDO CÓDIGO DO FORMULÁRIO: \n\nprivate void btnExibirMenorNumActionPerformed(java.awt.event.ActionEvent evt) {                                                  \n"
                        + "        objNumero.exibirMenorNumero();\n"
                        + "    }");

                JOptionPane.showMessageDialog(null, "MOSTRANDO CÓDIGO DO MÉTODO exibirMenorNumero(): \n\npublic void exibirMenorNumero() {\n"
                        + "        int menorNum = numerosAL.get(0);\n"
                        + "\n"
                        + "        if (!numerosAL.isEmpty()) { // verificando se o meu array não está vazio\n"
                        + "            for (int i = 0; i < numerosAL.size(); i++) {\n"
                        + "\n"
                        + "                // aqui se for menor\n"
                        + "                if (numerosAL.get(i) < menorNum) {\n"
                        + "                    menorNum = numerosAL.get(i);\n"
                        + "                }\n"
                        + "            }\n"
                        + "            JOptionPane.showMessageDialog(null, \"MENOR NÚMERO: \\n\\n\" + menorNum);\n"
                        + "        }\n"
                        + "    }");
                return;  
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atListaDeNumeros;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnApagarLista;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnExibirMaiorNum;
    private javax.swing.JButton btnExibirMedia;
    private javax.swing.JButton btnExibirMenorNum;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListarImpares;
    private javax.swing.JButton btnListarPares;
    private javax.swing.JButton btnListarTodos;
    private javax.swing.JButton btnOrdenarListaCrescente;
    private javax.swing.JButton btnOrdenarListaDecrescente;
    private javax.swing.JComboBox<String> comboCodigos;
    private javax.swing.JTextField edAddNome;
    private javax.swing.JTextField edCodAlterarNumero;
    private javax.swing.JTextField edCodDeletar;
    private javax.swing.JTextField edNovoNumero;
    private javax.swing.JTextField edNumero;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAddNovoNum;
    private javax.swing.JLabel lbAlterarNomeDeletar;
    private javax.swing.JLabel lbCodAlterarNumero;
    private javax.swing.JLabel lbExibirCódigo;
    private javax.swing.JLabel lbListaDeNumeros;
    private javax.swing.JLabel lbNovoNumero;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
